version: '3'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile # Путь к вашему Dockerfile для фронтенда
    ports:
      - "3000:3000" # Порт, на котором будет запущен ваш фронтенд (React)
